export default {
    LOGIN_CURRENT_USER: 'LOGIN_CURRENT_USER',
    REGISTRATION_NEW_USER: 'REGISTRATION_NEW_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    CHANGE_THEME: 'CHANGE_THEME',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    ADD_NEW_POST: 'ADD_NEW_POST',
    GET_POST: 'GET_POST',
    GET_USERS: 'GET_USERS',
    GET_USER: 'GET_USER',
    SELECT_ID_USER: 'SELECT_ID_USER',
    GET_POSTS: 'GET_POSTS',
    LIKE_POST: 'LIKE_POST',
    CHANGE_AVA: 'CHANGE_AVA',
    GET_COMMENTS: 'GET_COMMENTS',
    CREATE_POST: 'CREATE_POST'
}